<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        DB::table('productos')->insert([
            ['nombre_producto' => 'Comida perro 3kg',
             'marca'=>'VIUpets',
             'imagen'=>'comida.png',
             'descripcion'=>'Comida saludable de la propia clinica',
             'ficha_tecnica'=>'Saco de 3kg',
             'precio'=>'20.15',
             'cantidad_disponible'=>'10',
             'tipo_producto'=>'comida',
            ],
            ['nombre_producto' => 'Comida perro 6kg',
             'marca'=>'VIUpets',
             'imagen'=>'comida.png',
             'descripcion'=>'Comida saludable de la propia clinica',
             'ficha_tecnica'=>'Saco de 6kg',
             'precio'=>'40.99',
             'cantidad_disponible'=>'5',
             'tipo_producto'=>'comida',
            ],
            ['nombre_producto' => 'Comida gato 3kg',
             'marca'=>'VIUpets',
             'imagen'=>'comida.png',
             'descripcion'=>'Comida saludable de la propia clinica',
             'ficha_tecnica'=>'Saco de 3kg',
             'precio'=>'16',
             'cantidad_disponible'=>'13',
             'tipo_producto'=>'comida',
            ],
            ['nombre_producto' => 'Comida humeda',
             'marca'=>'VIUpets',
             'imagen'=>'comida-humeda.png',
             'descripcion'=>'Comida saludable de la propia clinica',
             'ficha_tecnica'=>'Lata individual',
             'precio'=>'1.99',
             'cantidad_disponible'=>'20',
             'tipo_producto'=>'comida',
            ],
            ['nombre_producto' => 'Correa roja',
             'marca'=>'Kiwoko',
             'imagen'=>'correa-roja.png',
             'descripcion'=>'Correa de color rojo',
             'ficha_tecnica'=>'No es extensible',
             'precio'=>'22.99',
             'cantidad_disponible'=>'4',
             'tipo_producto'=>'accesorio',
            ],
            ['nombre_producto' => 'Trasportin tela mediano',
             'marca'=>'Kiwoko',
             'imagen'=>'trasportin-tela.png',
             'descripcion'=>'Trasportin de tela de tamaño mediano',
             'ficha_tecnica'=>'Muy recomendable para gatos',
             'precio'=>'35',
             'cantidad_disponible'=>'2',
             'tipo_producto'=>'accesorio',
            ],
            ['nombre_producto' => 'Corta uñas',
             'marca'=>'VIUpets',
             'imagen'=>'cortauñas.png',
             'descripcion'=>'Corta uñas de mascota',
             'ficha_tecnica'=>'Corta uñas',
             'precio'=>'5.99',
             'cantidad_disponible'=>'6',
             'tipo_producto'=>'accesorio',
            ],
            ['nombre_producto' => 'Desparasitador gato',
             'marca'=>'FarmaciaAnimal',
             'imagen'=>'desparasitador.png',
             'descripcion'=>'Desparasitador gato super rapido y eficaz',
             'ficha_tecnica'=>'Apto para gatos de hasta 7kg',
             'precio'=>'16.25',
             'cantidad_disponible'=>'28',
             'tipo_producto'=>'medicamento',
            ],
            ['nombre_producto' => 'Desparasitador perro',
             'marca'=>'FarmaciaAnimal',
             'imagen'=>'desparasitador.png',
             'descripcion'=>'Desparasitador perro super rapido y eficaz',
             'ficha_tecnica'=>'Apto para perros de hasta 15kg',
             'precio'=>'17',
             'cantidad_disponible'=>'32',
             'tipo_producto'=>'medicamento',
            ],
            ['nombre_producto' => 'Rabia',
             'marca'=>'FarmaciaAnimal',
             'imagen'=>'vacuna-rabia.png',
             'descripcion'=>'Vacuna de la rabia',
             'ficha_tecnica'=>'Rabia',
             'precio'=>'33',
             'cantidad_disponible'=>'42',
             'tipo_producto'=>'vacunas',
            ],
            ['nombre_producto' => 'Trivalente',
            'marca'=>'FarmaciaAnimal',
            'imagen'=>'vacuna-trivalente.png',
            'descripcion'=>'Vacuna trivalente gatos',
            'ficha_tecnica'=>'FHV-1, FPV y FCV',
            'precio'=>'40',
            'cantidad_disponible'=>'35',
            'tipo_producto'=>'vacunas',
           ],
           ['nombre_producto' => 'Polivalente',
           'marca'=>'FarmaciaAnimal',
           'imagen'=>'vacuna-polivalente.png',
           'descripcion'=>'Vacuna polivalente perro',
           'ficha_tecnica'=>'parvovirus, virus del moquillo, virus de Parainfluenza, virus de la hepatitis y leptospira',
           'precio'=>'40',
           'cantidad_disponible'=>'37',
           'tipo_producto'=>'vacunas',
          ],
          ['nombre_producto' => 'Cepillo',
           'marca'=>'VIUpets',
           'imagen'=>'cepillo.png',
           'descripcion'=>'Cepillo para gatos',
           'ficha_tecnica'=>'Puas pequeñas',
           'precio'=>'6.99',
           'cantidad_disponible'=>'10',
           'tipo_producto'=>'peluqueria',
          ],
          ['nombre_producto' => 'Champú perro',
          'marca'=>'Kiwoko',
          'imagen'=>'champu.png',
          'descripcion'=>'Champú perros olor natural',
          'ficha_tecnica'=>'Champú hipoalergénico, apto para todo tipo de pieles',
          'precio'=>'12',
          'cantidad_disponible'=>'5',
          'tipo_producto'=>'peluqueria',
         ],


        ]);
    }
}